title BigCo, Inc. Onboarding API

Home->+WIP: startOnBoarding
WIP->+companyData: collectCompanyData
companyData-->-WIP: saveToWIP
WIP->+accountData: collectAccountData
accountData-->-WIP: saveToWIP
WIP->+activityData: collectActivityData
activityData-->-WIP: saveToWIP
WIP-->+finalizeWIP: completeOnboarding
finalizeWIP->-Home: goHome
WIP->+cancelWIP: abandonOnboarding
cancelWIP-->-Home: goHome
